-- 9.3

-- i)
CREATE CLUSTERED INDEX IxSsn ON EMPLOYEE(Ssn);

-- ii)
CREATE CLUSTERED INDEX IxName ON EMPLOYEE(Fname, Lname);

-- iii)
CREATE INDEX IxDno EMPLOYEE(Dno);
CREATE CLUSTERED INDEX IxDnumber ON DEPARTMENT(Dnumber);

-- iv)
CREATE INDEX IxPno WORKS_ON(Pno);
CREATE CLUSTERED INDEX IxPnum ON PROJECT(Pnumber);

-- v)
CREATE CLUSTERED INDEX IxEssn ON DEPENDENT(Essn);

-- vi)
CREATE CLUSTERED INDEX IxDnum ON PROJECT(Dnum);
