CREATE TABLE PESSOA(
	numCC INT NOT NULL,
	morada VarChar(50) NOT NULL,
	dataNasc DATE NOT NULL,
	nome VarChar(30) NOT NULL,
	PRIMARY KEY (numCC)
	);

CREATE TABLE ALUNO(
	numCC INT REFERENCES PESSOA(numCC) NOT NULL,
	PRIMARY KEY(numCC)
	);

CREATE TABLE PROFESSOR(
	numCC INT REFERENCES PESSOA(numCC) NOT NULL,
	email VarChar(50) NOT NULL,
	numFun INT NOT NULL,
	contacto INT NOT NULL,
	PRIMARY KEY(numCC)
	);


CREATE TABLE LISTA(
	entrega BIT,
	levanta BIT,
	PRIMARY KEY(entrega,levanta)
	);


CREATE TABLE ENCARREGADOEDUCACAO(
	numCC INT REFERENCES PESSOA(numCC) NOT NULL,
	email VarChar(50) NOT NULL,
	contacto INT NOT NULL,
	relacao VarChar(20) NOT NULL,
	FK_PessoaAutLevantar BIT,
	FK_PessoaAutEntregar BIT,
	FOREIGN KEY (FK_PessoaAutLevantar,FK_PessoaAutEntregar) REFERENCES LISTA(levanta,entrega),
	PRIMARY KEY(numCC)
	);

CREATE TABLE TURMA(
	id INT NOT NULL,
	anoLetivo INT NOT NULL,
	designacao CHAR(3) NOT NULL,
	FK_Prof INT REFERENCES PROFESSOR(numCC) NOT NULL,
	FK_Aluno INT REFERENCES ALUNO(numCC) NOT NULL,
	PRIMARY KEY(id)
	);

CREATE TABLE TEM1(
	numMax INT NOT NULL,
	id1 INT REFERENCES TURMA(id) NOT NULL,
	numCC1 INT REFERENCES ALUNO(numCC) NOT NULL,
	PRIMARY KEY(id1,numCC1)
	);

CREATE TABLE ATIVIDADE(
	id INT NOT NULL,
	custo INT NOT NULL,
	designacao VarChar(20) NOT NULL,
	FK_TURMA INT REFERENCES TURMA(id) NOT NULL,
	PRIMARY KEY(id)
	);

CREATE TABLE TEM2(
	id1 INT REFERENCES TURMA(id) NOT NULL,
	id2 INT REFERENCES ATIVIDADE(id) NOT NULL,
	PRIMARY KEY(id1,id2)
	);


